---
services:
  nebula-sync:
    env_file:
    - .env
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    environment:
    - TZ=Europe/Amsterdam
